package cn.pogotravel.shihe.mapper;

import cn.pogotravel.shihe.model.NotificationOne;
import cn.pogotravel.shihe.model.NotificationOneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NotificationOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    long countByExample(NotificationOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int deleteByExample(NotificationOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int insert(NotificationOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int insertSelective(NotificationOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    List<NotificationOne> selectByExampleWithRowbounds(NotificationOneExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    List<NotificationOne> selectByExample(NotificationOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    NotificationOne selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") NotificationOne record, @Param("example") NotificationOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int updateByExample(@Param("record") NotificationOne record, @Param("example") NotificationOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int updateByPrimaryKeySelective(NotificationOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationone
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    int updateByPrimaryKey(NotificationOne record);
}