package cn.pogotravel.shihe.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentId
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentator
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtcreate
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmtModified
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long gmtmodified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likeCount
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentcount
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Integer commentcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentId
     *
     * @return the value of comment.parentId
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentId
     *
     * @param parentid the value for comment.parentId
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentator
     *
     * @return the value of comment.commentator
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentator
     *
     * @param commentator the value for comment.commentator
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtcreate
     *
     * @return the value of comment.gmtcreate
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtcreate
     *
     * @param gmtcreate the value for comment.gmtcreate
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmtModified
     *
     * @return the value of comment.gmtModified
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmtModified
     *
     * @param gmtmodified the value for comment.gmtModified
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setGmtmodified(Long gmtmodified) {
        this.gmtmodified = gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likeCount
     *
     * @return the value of comment.likeCount
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likeCount
     *
     * @param likecount the value for comment.likeCount
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setLikecount(Long likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentcount
     *
     * @return the value of comment.commentcount
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentcount
     *
     * @param commentcount the value for comment.commentcount
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }
}