package cn.pogotravel.shihe.model;

public class NotificationOne {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.id
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.notifier
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.receiver
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.outerId
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.type
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.status
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.gmtcreate
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.notifiername
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private String notifiername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationone.outertitle
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    private String outertitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.id
     *
     * @return the value of notificationone.id
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.id
     *
     * @param id the value for notificationone.id
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.notifier
     *
     * @return the value of notificationone.notifier
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.notifier
     *
     * @param notifier the value for notificationone.notifier
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.receiver
     *
     * @return the value of notificationone.receiver
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.receiver
     *
     * @param receiver the value for notificationone.receiver
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.outerId
     *
     * @return the value of notificationone.outerId
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.outerId
     *
     * @param outerid the value for notificationone.outerId
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.type
     *
     * @return the value of notificationone.type
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.type
     *
     * @param type the value for notificationone.type
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.status
     *
     * @return the value of notificationone.status
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.status
     *
     * @param status the value for notificationone.status
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.gmtcreate
     *
     * @return the value of notificationone.gmtcreate
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.gmtcreate
     *
     * @param gmtcreate the value for notificationone.gmtcreate
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.notifiername
     *
     * @return the value of notificationone.notifiername
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public String getNotifiername() {
        return notifiername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.notifiername
     *
     * @param notifiername the value for notificationone.notifiername
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setNotifiername(String notifiername) {
        this.notifiername = notifiername == null ? null : notifiername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationone.outertitle
     *
     * @return the value of notificationone.outertitle
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public String getOutertitle() {
        return outertitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationone.outertitle
     *
     * @param outertitle the value for notificationone.outertitle
     *
     * @mbg.generated Sat Apr 04 23:11:29 CST 2020
     */
    public void setOutertitle(String outertitle) {
        this.outertitle = outertitle == null ? null : outertitle.trim();
    }
}